//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MazeGame_Final.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MazeGame_Final.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap A_knight_in_a_maze {
            get {
                object obj = ResourceManager.GetObject("A knight in a maze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap backGroundMenu2 {
            get {
                object obj = ResourceManager.GetObject("backGroundMenu2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cloudy {
            get {
                object obj = ResourceManager.GetObject("cloudy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coin {
            get {
                object obj = ResourceManager.GetObject("coin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream coin_claim {
            get {
                return ResourceManager.GetStream("coin_claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DoorWin {
            get {
                object obj = ResourceManager.GetObject("DoorWin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap easy_btn {
            get {
                object obj = ResourceManager.GetObject("easy_btn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11
        ///0 0 0 0 0 0 0 0 0 0 0 
        ///0 0 0 0 0 0 2 1 1 2 3
        ///0 0 1 1 1 2 4 0 1 0 0
        ///0 0 1 0 1 0 0 0 1 0 0
        ///0 0 1 0 1 1 0 0 1 0 0
        ///0 1 1 0 0 1 1 0 1 0 0
        ///0 1 0 0 0 0 2 0 1 0 0
        ///0 1 1 1 1 1 1 0 1 0 0
        ///0 0 0 0 0 0 1 0 4 0 0
        ///0 2 4 1 1 1 1 1 1 0 0
        ///0 3 0 0 0 0 0 0 0 0 0 
        ///
        ///Cháu trai của cháu gái của bà cố ngoại  bạn là anh em họ thứ hai của bạn đúng hay sai ? 
        ///false
        ///Anh trai của cháu gái gọi bạn là chú là cháu của bạn đúng hay sai ? 
        ///true
        ///Gieo hai con xúc xắc cân đối. Xác suất để có đúng 1 con xúc xắc xuất hiện mặt  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string easy1 {
            get {
                return ResourceManager.GetString("easy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11
        ///0 0 0 0 0 0 0 0 0 0 0 
        ///0 0 0 0 0 0 1 1 1 2 3
        ///0 0 4 1 1 2 4 0 1 0 0
        ///0 0 1 0 1 0 0 0 1 0 0
        ///0 0 1 0 1 1 0 0 1 0 0
        ///0 1 1 0 0 1 1 0 1 0 0
        ///0 1 0 0 0 0 1 0 1 0 0
        ///0 1 1 1 1 1 1 0 1 0 0
        ///0 0 0 0 0 0 1 0 4 0 0
        ///0 4 1 1 1 1 2 1 1 0 0
        ///0 0 0 0 0 0 3 0 0 0 0 
        ///
        ///Trong Dragon Ball Z, khi nói về lực chiến thì nhân vật vegeta được cho là mạnh nhất đúng hay sai ?
        ///false
        ///Trong One Piece, Luffy là nhân vật chính đúng hay sai ? 
        ///true
        ///Oda kishimoto là tác giả của bộ truyện tranh naruto đúng hay sai ? 
        ///false
        ///
        ///.
        /// </summary>
        internal static string easy2 {
            get {
                return ResourceManager.GetString("easy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11
        ///0 0 0 0 0 0 0 0 0 0 0
        ///0 4 1 1 1 1 0 0 1 4 0
        ///0 0 1 1 0 1 1 1 1 0 0
        ///0 3 0 1 0 4 1 0 1 0 0
        ///0 2 4 1 0 1 1 1 1 1 0
        ///0 0 0 0 4 1 0 0 0 1 0
        ///0 0 0 0 0 1 0 0 0 1 0
        ///0 0 4 0 1 1 0 1 1 1 0
        ///0 0 1 0 1 1 0 1 0 0 0
        ///0 3 1 1 2 0 0 1 4 4 0
        ///0 0 0 0 0 0 0 0 0 0 0
        ///
        ///Tokyo là thủ đô của Nhật Bản đúng không?
        ///false
        ///Bánh mì ngon số dzách đúng không?
        ///true.
        /// </summary>
        internal static string easy3 {
            get {
                return ResourceManager.GetString("easy3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11
        ///0 0 0 0 0 0 0 0 0 0 0
        ///0 0 4 1 1 1 0 0 2 3 0
        ///0 0 1 0 0 1 0 0 1 0 0
        ///0 0 1 0 0 1 0 0 1 0 0
        ///0 4 1 0 4 1 1 1 1 1 0
        ///0 0 1 0 0 1 1 1 0 1 0
        ///0 1 1 0 0 4 1 1 1 0 0
        ///0 0 0 0 0 1 0 0 1 1 0
        ///0 1 2 1 0 1 0 0 0 1 0
        ///0 3 0 1 1 1 0 4 1 1 0
        ///0 0 0 0 0 0 0 0 0 0 0
        ///
        ///Đom đóm phát sáng khi Jack hát đúng không?
        ///true
        ///Bạn đẹp trai đúng không?
        ///true
        ///
        ///.
        /// </summary>
        internal static string easy4 {
            get {
                return ResourceManager.GetString("easy4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11
        ///0 0 0 0 0 0 0 0 3 0 0
        ///0 1 1 0 0 0 1 2 1 1 0
        ///0 4 0 1 4 4 1 0 0 0 0
        ///0 1 0 1 0 1 0 0 1 1 0
        ///0 1 1 0 0 1 0 1 1 0 0
        ///0 0 4 1 1 1 0 4 0 1 0
        ///0 0 1 0 0 0 0 4 0 1 0
        ///0 0 4 2 4 4 0 4 1 1 0
        ///0 0 0 4 0 1 1 1 0 1 0
        ///0 1 1 4 0 0 0 4 1 1 0
        ///0 3 0 0 0 0 0 0 0 0 0
        ///
        ///Lịch sử Việt Nam có 4 triều đại phong kiến lớn là: Lý, Trần, Lê, Nguyễn đúng hay sai?
        ///true
        ///Trần Quốc Toản là người đã bóp nát quả cam khi nghe tin giặc Nguyên Mông xâm lược đúng hay sai?
        ///true
        ///.
        /// </summary>
        internal static string easy5 {
            get {
                return ResourceManager.GetString("easy5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11
        ///0 3 0 0 0 0 0 0 0 0 0
        ///0 1 0 1 1 1 1 1 1 1 0
        ///0 2 0 1 0 0 0 0 1 0 0
        ///0 1 0 1 0 1 0 0 1 1 0
        ///0 1 0 1 0 4 1 1 0 1 0
        ///0 4 0 4 0 1 0 1 0 1 0
        ///0 4 1 1 1 4 0 0 2 1 0
        ///0 0 0 4 0 0 1 1 4 0 0
        ///0 0 1 1 1 0 1 0 4 0 0
        ///0 0 4 0 1 4 1 0 1 1 3
        ///0 0 0 0 0 0 0 0 0 0 0
        ///
        ///Việt Nam có đường bờ biển dài hơn 3.000 km đúng hay sai?
        ///true
        ///Sông Hồng là con sông dài nhất Việt Nam đúng hay sai?
        ///false.
        /// </summary>
        internal static string easy6 {
            get {
                return ResourceManager.GetString("easy6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11
        ///0 0 0 0 0 0 0 0 0 0 0
        ///0 1 0 1 1 1 0 1 2 1 0
        ///0 1 0 1 0 1 1 1 0 1 0
        ///0 1 0 4 0 1 0 1 0 1 3
        ///0 1 0 1 0 4 1 1 0 0 0
        ///0 1 0 1 0 1 0 1 0 1 0
        ///0 1 0 1 0 1 0 0 0 1 0
        ///0 1 1 1 0 1 1 4 1 1 0
        ///0 0 4 0 0 1 0 0 0 1 0
        ///0 1 1 0 1 2 1 0 1 1 0
        ///0 0 0 0 3 0 0 0 0 0 0
        ///
        ///Bác Hồ ra đi tìm đường cứu nước ngày 05/06/1911 đúng hay sai ?
        ///true
        ///ngày 2/9/1945 Chủ tịch Hồ Chí Minh đọc bản Tuyên ngôn Độc lập, khai sinh ra nước Việt Nam Dân chủ Cộng hòa đúng hay sai ?
        ///true.
        /// </summary>
        internal static string easy7 {
            get {
                return ResourceManager.GetString("easy7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11
        ///0 0 0 0 0 0 0 0 0 0 0
        ///0 1 0 1 1 1 0 1 1 1 0
        ///0 1 1 1 0 4 1 1 0 0 0
        ///0 1 0 0 1 0 0 1 1 1 0
        ///0 0 0 1 1 1 1 0 1 0 0
        ///0 0 0 1 0 1 0 1 1 1 0
        ///0 1 4 1 0 1 0 1 0 1 0
        ///0 0 1 0 0 1 0 1 0 1 0
        ///0 1 2 1 1 1 1 4 0 1 0
        ///0 1 0 1 0 1 0 1 2 1 0
        ///0 3 0 0 0 0 0 0 3 0 0
        ///
        ///Bác Hồ chỉ nói được mỗi tiếng anh đúng hay sai?
        ///false
        ///Bác Hồ mất vào năm 1969 đúng hay sai?
        ///true
        ///.
        /// </summary>
        internal static string easy8 {
            get {
                return ResourceManager.GetString("easy8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap floor {
            get {
                object obj = ResourceManager.GetObject("floor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 1 1 4 0 0 0 1 1 1 1 1 1 1 1 1 1 1 4 0
        ///0 0 0 1 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 1 0
        ///0 0 0 1 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 1 0 0 0 0 0 0 4 0 0 0 1 1 1 0
        ///0 0 1 1 1 1 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0
        ///0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0
        ///0 0 1 0 0 0 0 0 0 1 1 1 1 1 0 0 0 1 0 0 0
        ///0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 
        ///0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hard1 {
            get {
                return ResourceManager.GetString("hard1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 1 1 4 0 0 0 1 1 1 1 1 1 1 1 1 1 1 4 0
        ///0 0 0 1 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 1 0
        ///0 0 0 1 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 1 0 0 0 0 0 0 4 0 0 0 1 1 1 0
        ///0 0 1 1 1 1 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0
        ///0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0
        ///0 0 1 0 0 0 0 0 0 1 1 1 1 1 0 0 0 1 0 0 0
        ///0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 
        ///0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hard2 {
            get {
                return ResourceManager.GetString("hard2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 1 4 1 1 1 4 0 0 0 0 0 0 0 1 1 3 0 0
        ///0 0 0 1 0 1 0 0 1 4 2 1 1 0 0 1 1 0 0 0 0
        ///0 0 0 1 0 1 0 0 1 0 0 0 1 2 1 1 0 0 0 0 0
        ///0 4 4 1 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0
        ///0 4 0 0 0 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0
        ///0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 2 1 2 0 0 0 0 1 0 0 1 1 1 1 1 1 0 0
        ///0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0
        ///0 0 0 1 0 1 1 4 1 1 1 1 0 1 0 0 0 1 1 0 0
        ///0 0 0 4 0 1 0 0 0 0 1 0 0 1 1 0 0 0 1 0 0
        ///0 4 4 4 0 4 0 0 1 1 1 0 0 0 1 1 0 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hard3 {
            get {
                return ResourceManager.GetString("hard3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 4 1 1 1 3 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0
        ///0 4 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0
        ///0 1 0 0 4 1 1 2 1 0 0 0 1 0 0 0 0 0 0 3 0
        ///0 1 0 0 4 0 0 0 1 1 0 0 2 0 0 1 1 2 1 1 0
        ///0 4 0 0 4 0 0 0 0 1 0 0 3 0 0 1 0 0 0 0 0
        ///0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0
        ///0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0
        ///0 1 0 4 1 1 1 1 1 1 0 0 1 0 0 1 0 0 0 0 0
        ///0 1 0 0 0 4 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0
        ///0 1 1 1 1 4 0 0 0 1 0 0 1 1 1 1 1 1 0 0 0
        ///0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hard4 {
            get {
                return ResourceManager.GetString("hard4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 4 1 1 1 0 0 0 1 4 4 1 1 0 0 1 3
        ///0 0 1 1 1 1 0 0 1 0 4 1 1 0 0 0 4 0 2 4 0
        ///0 0 1 0 0 1 0 1 4 1 1 0 1 0 0 0 4 0 1 0 0
        ///0 0 1 0 0 0 0 4 0 0 0 0 1 1 1 0 1 4 1 0 0
        ///0 1 1 1 1 1 0 1 1 0 4 1 0 0 4 1 1 0 1 1 0
        ///0 0 0 1 0 1 0 0 1 0 4 0 1 4 1 0 0 0 0 0 0
        ///0 0 0 4 0 0 0 4 1 1 4 0 1 0 0 0 1 4 4 0 0
        ///0 1 4 4 1 4 0 4 0 0 0 0 4 1 1 1 4 0 1 4 0
        ///0 1 0 0 0 1 0 1 4 0 1 0 1 0 0 0 1 0 0 1 0
        ///0 4 0 1 4 1 0 0 1 4 1 0 1 0 0 1 1 0 0 0 0
        ///0 1 0 0 0 1 4 1 0 0 1 1 1 1 1 0 1 4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hard5 {
            get {
                return ResourceManager.GetString("hard5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 1 1 0 4 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0
        ///0 0 1 4 1 1 1 0 4 0 4 1 4 1 4 0 4 1 1 4 0
        ///0 0 1 0 0 0 1 0 4 0 0 0 1 0 1 0 0 0 0 1 0
        ///0 1 1 4 1 0 1 1 4 1 1 1 1 0 1 4 4 1 1 1 0
        ///0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 4 0 0
        ///0 1 1 0 1 4 4 1 1 4 1 1 4 0 4 4 4 1 1 0 0
        ///0 0 4 0 0 0 0 0 0 0 0 0 4 0 1 0 0 0 4 0 0
        ///0 0 4 4 1 0 1 1 1 0 4 1 1 4 4 0 1 1 4 4 0
        ///0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0
        ///0 1 4 4 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 4 0
        ///0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hard6 {
            get {
                return ResourceManager.GetString("hard6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 1 1 1 1 1 0 1 1 0 1 0 1 1 1 0 1 0 1 1 0
        ///0 0 0 1 0 1 1 1 0 0 1 0 1 0 1 0 1 0 1 0 0
        ///0 1 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 1 1 0
        ///0 1 0 0 1 1 4 1 0 1 0 0 1 0 0 0 0 0 0 1 0
        ///0 1 0 1 1 0 1 0 0 1 1 0 1 1 0 1 1 1 0 1 0
        ///0 1 1 0 0 1 1 1 0 0 0 1 0 1 0 0 1 0 0 1 0
        ///0 0 1 0 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 0
        ///0 1 1 1 0 1 1 0 0 0 1 0 0 1 0 0 0 1 0 1 0
        ///0 1 0 1 0 0 0 1 0 0 1 0 1 1 1 1 1 1 0 0 0
        ///0 1 0 1 1 1 1 1 1 1 1 1 0 0 1 0 0 1 1 4 0
        ///0 0 1 1 0 1 0 1 0 1 0 0 1 1 1 1 1 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hard7 {
            get {
                return ResourceManager.GetString("hard7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0
        ///0 1 0 1 1 0 4 0 1 1 1 0 2 1 0 0 1 1 1 1 0
        ///0 1 1 0 1 1 1 1 1 0 1 1 1 0 0 1 1 0 0 1 0
        ///0 0 1 0 0 1 1 1 0 0 0 1 0 4 0 0 1 0 1 1 0
        ///0 1 1 1 1 0 1 0 4 1 1 1 1 1 1 0 0 0 1 0 0
        ///0 0 1 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1 1 1 0
        ///0 1 1 0 1 1 4 0 0 1 1 0 1 1 1 0 1 0 1 0 0
        ///0 4 0 1 0 0 1 0 1 0 1 0 1 0 1 4 1 0 0 1 0
        ///0 1 1 1 1 0 1 1 1 0 1 1 1 0 1 0 0 1 1 1 0
        ///0 0 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 1 0 1 0
        ///0 1 1 1 0 1 0 1 1 1 1 1 1 1 0 1 0 1 0 1 0
        ///0 1 0 0 1 0 0 1 0 0 0 1 0 1 0 1 1 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hard8 {
            get {
                return ResourceManager.GetString("hard8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap health {
            get {
                object obj = ResourceManager.GetObject("health", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap intro_back_main {
            get {
                object obj = ResourceManager.GetObject("intro_back_main", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap introBack {
            get {
                object obj = ResourceManager.GetObject("introBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kdead {
            get {
                object obj = ResourceManager.GetObject("kdead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kdown {
            get {
                object obj = ResourceManager.GetObject("kdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kleft {
            get {
                object obj = ResourceManager.GetObject("kleft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kright {
            get {
                object obj = ResourceManager.GetObject("kright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kup {
            get {
                object obj = ResourceManager.GetObject("kup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap land {
            get {
                object obj = ResourceManager.GetObject("land", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
        ///0 4 1 0 0 0 0 0 0 0 0 0 1 4 0 
        ///0 0 1 1 1 1 1 0 0 0 0 0 1 0 0 
        ///0 0 0 1 0 0 0 0 0 0 0 0 1 0 0
        ///0 1 1 1 0 0 0 0 0 0 0 0 1 0 0
        ///0 1 0 1 1 1 1 0 0 1 1 1 1 0 0 
        ///0 1 1 1 0 0 1 0 0 1 0 0 1 0 0 
        ///0 0 0 1 0 0 1 1 1 1 0 0 1 0 0 
        ///0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 
        ///0 0 0 1 0 0 0 0 0 1 1 1 1 0 0
        ///3 2 4 1 1 1 0 0 0 1 0 0 1 0 0 
        ///0 0 0 0 0 1 0 0 0 1 0 0 1 0 0
        ///0 0 0 0 0 1 1 1 1 1 0 0 1 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 4 2 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 3 0
        ///
        ///Đơn vị tiền tệ cùa Pháp hiện tại  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string medium1 {
            get {
                return ResourceManager.GetString("medium1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15
        ///0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 
        ///0 4 0 0 0 0 0 0 0 0 2 0 0 0 0 
        ///0 1 1 1 1 1 1 1 1 1 1 1 1 1 0
        ///0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
        ///0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
        ///0 1 1 1 1 0 0 0 0 0 0 0 0 1 0
        ///0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
        ///0 0 0 0 1 1 1 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 0 1 0 0 0 0 0 1 0
        ///0 0 0 0 0 0 0 1 1 4 1 1 1 1 0
        ///0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
        ///3 2 1 0 0 0 0 1 0 0 0 0 0 0 0
        ///0 0 1 0 0 0 0 1 0 0 0 0 0 0 0
        ///0 0 1 1 1 1 1 1 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///
        ///Có nhận xét sau : &quot;Con Game này của chú [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string medium2 {
            get {
                return ResourceManager.GetString("medium2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 4 1 1 1 0 0 4 0 3 0 0 0 0 0
        ///0 3 0 0 1 1 0 1 0 2 0 0 0 0 0
        ///0 0 0 0 0 1 0 1 0 1 0 0 0 0 0
        ///0 1 1 1 0 1 1 1 0 1 1 1 1 0 0
        ///0 1 1 4 1 1 0 0 0 0 0 0 1 1 0
        ///0 4 1 0 4 1 4 1 1 0 1 1 4 0 0
        ///0 1 1 0 1 4 1 1 1 4 1 1 1 1 0
        ///0 1 1 1 4 0 0 1 1 0 1 0 1 1 0
        ///0 1 4 1 0 1 1 1 1 0 4 1 1 4 0
        ///0 0 1 1 1 1 1 0 4 1 0 1 1 4 0
        ///0 0 1 0 0 1 0 0 1 0 0 0 0 0 0
        ///0 0 1 0 0 1 0 0 1 0 0 0 0 0 0
        ///0 2 1 0 3 1 0 0 2 1 1 4 1 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///
        ///Bác Hồ sinh ngày 19/5/1890 đúng không?
        ///t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string medium3 {
            get {
                return ResourceManager.GetString("medium3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 4 4 4 1 1 0 4 0 0 3 1 0 0 0
        ///0 0 0 0 0 1 0 1 1 0 0 1 0 0 0
        ///0 0 4 2 1 1 1 0 1 0 0 4 0 0 0
        ///0 0 1 0 0 0 1 0 1 0 0 1 0 0 0
        ///0 0 1 0 0 0 1 0 1 0 0 1 0 0 0
        ///0 1 1 0 0 0 1 1 1 0 0 2 0 0 0
        ///0 1 0 0 1 1 1 0 1 1 1 1 0 0 0
        ///0 4 0 0 1 0 1 0 0 0 0 1 0 3 0
        ///0 4 0 0 1 0 1 0 0 0 0 1 0 2 0
        ///0 0 1 1 1 0 1 1 1 1 0 1 1 1 0
        ///0 0 1 0 0 0 0 0 0 1 0 0 0 0 0
        ///0 0 1 0 1 4 1 0 0 1 1 4 1 0 0
        ///0 0 0 0 3 0 1 1 1 1 0 0 1 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///
        ///Trường Sa, Hoàng Sa là của Việt Nam?
        ///tru [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string medium4 {
            get {
                return ResourceManager.GetString("medium4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 1 0 4 1 0 1 0 0 0 0 1 1 0
        ///0 1 4 0 0 1 0 4 1 4 1 4 1 0 0
        ///0 1 0 1 1 1 0 1 0 4 0 0 1 1 0
        ///0 1 1 4 0 0 0 1 0 4 0 0 0 4 0
        ///0 0 0 4 1 1 0 1 0 1 4 0 1 1 0
        ///0 0 0 0 0 1 0 0 0 1 0 4 1 0 0
        ///3 1 2 4 0 1 4 1 0 1 4 1 0 0 0
        ///0 0 0 4 0 0 0 4 0 1 0 0 0 1 0
        ///0 1 1 1 1 4 0 1 1 4 0 1 2 4 3
        ///0 1 0 0 0 0 0 4 0 0 1 4 0 1 0
        ///0 1 0 0 1 1 4 1 1 1 1 0 1 1 0
        ///0 1 1 1 4 0 0 0 0 1 0 1 1 0 0
        ///0 1 0 0 1 1 1 1 0 1 0 4 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
        ///
        ///Cuộc cách mạng công nghiệp lần thứ nhất  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string medium5 {
            get {
                return ResourceManager.GetString("medium5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15
        ///0 0 0 0 0 0 3 0 0 0 0 0 0 0 0
        ///0 4 0 4 4 4 1 0 1 1 1 0 0 0 0
        ///0 4 0 0 0 2 0 0 1 0 1 1 1 1 0
        ///0 1 1 1 1 4 0 4 1 0 0 0 0 1 0
        ///0 0 0 1 0 1 0 1 0 0 0 1 0 1 0
        ///0 1 4 4 0 4 4 4 0 1 4 4 1 1 0
        ///0 0 0 4 0 0 0 0 0 1 0 0 1 0 0
        ///0 1 0 4 0 1 1 1 4 4 0 1 4 0 0
        ///0 1 1 1 0 1 0 0 0 0 0 0 1 0 0
        ///0 0 1 0 0 1 4 4 0 1 4 1 0 1 0
        ///0 1 1 0 0 0 0 1 0 1 0 1 4 1 0
        ///0 0 1 1 4 4 4 1 4 1 0 0 4 0 0
        ///0 0 1 0 0 0 0 4 0 0 1 1 4 1 0
        ///0 1 2 0 1 4 1 4 1 1 1 0 0 1 0
        ///0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 
        ///
        ///Đỉnh núi Everest nằm ở nước Ấn Độ đúng h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string medium6 {
            get {
                return ResourceManager.GetString("medium6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 1 0 1 1 1 0 1 0 1 0 1 0 1 0
        ///0 1 1 1 0 1 1 1 1 1 1 1 1 1 0
        ///0 0 1 0 0 0 0 0 1 0 0 1 0 0 0
        ///0 0 1 1 1 0 1 1 1 1 0 1 1 1 0
        ///0 0 0 0 1 0 0 1 0 1 0 0 1 0 0
        ///0 1 1 1 1 1 0 1 0 0 0 1 1 1 0
        ///0 1 0 0 0 1 0 1 1 1 0 1 0 1 0
        ///0 1 1 1 0 1 0 1 0 1 0 1 0 1 0
        ///0 0 0 1 0 1 1 1 0 1 1 1 0 1 0
        ///0 1 1 1 1 4 0 0 0 1 0 0 0 1 0
        ///0 1 0 1 0 0 0 1 1 1 0 1 4 1 0
        ///0 1 1 1 1 1 1 1 0 1 1 1 0 0 0
        ///0 1 0 2 0 1 0 1 0 1 0 1 2 1 0
        ///0 0 0 3 0 0 0 0 0 0 0 0 3 0 0
        ///
        ///Tên khai sinh của Bác Hồ là Nguyễn Sinh C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string medium7 {
            get {
                return ResourceManager.GetString("medium7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 1 2 0 1 0 1 0 1 1 1 1 1 1 0
        ///0 0 1 1 1 1 2 0 0 1 0 0 1 0 0
        ///0 1 1 0 0 0 1 1 4 1 1 1 1 1 0
        ///0 0 1 1 1 0 0 0 1 0 0 0 0 1 0
        ///0 1 0 1 0 1 1 1 1 1 2 0 1 1 0
        ///0 1 1 1 0 1 0 1 0 0 1 0 1 0 0
        ///0 0 0 0 1 1 1 1 1 0 1 0 0 1 0
        ///0 1 1 1 0 0 0 2 0 1 1 1 1 1 0
        ///0 1 0 1 1 4 1 1 0 0 1 0 1 0 0
        ///0 1 0 1 0 1 0 1 1 2 1 0 1 1 0
        ///0 1 1 1 0 1 1 0 0 1 0 1 0 4 0
        ///0 0 0 1 0 0 2 1 0 1 1 0 0 1 0
        ///0 1 1 1 1 1 0 1 1 1 0 1 2 1 0
        ///0 0 0 0 0 0 0 0 3 0 0 3 0 0 0
        ///
        ///Lãnh thổ Việt Nam có chiều dài xấp xỉ 1.7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string medium8 {
            get {
                return ResourceManager.GetString("medium8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Menu_back {
            get {
                object obj = ResourceManager.GetObject("Menu_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Menu_back1 {
            get {
                object obj = ResourceManager.GetObject("Menu_back1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream move {
            get {
                return ResourceManager.GetStream("move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream move1 {
            get {
                return ResourceManager.GetStream("move1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream move2 {
            get {
                return ResourceManager.GetStream("move2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quiz {
            get {
                object obj = ResourceManager.GetObject("quiz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream quiz1 {
            get {
                return ResourceManager.GetStream("quiz1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream quiz2 {
            get {
                return ResourceManager.GetStream("quiz2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tree {
            get {
                object obj = ResourceManager.GetObject("tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wall {
            get {
                object obj = ResourceManager.GetObject("wall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
